# Generated by Django 3.1.7 on 2021-03-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='merchant.merchantprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(max_length=20)),
                ('last_logged_device', models.CharField(max_length=100)),
                ('last_active', models.DateField(default=django.utils.timezone.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='merchant.merchantprofile')),
                ('operator_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.operatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sender_account', models.CharField(blank=True, default='', max_length=30)),
                ('receiver_account', models.CharField(blank=True, default='', max_length=30)),
                ('destination_bank', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('currency', models.CharField(blank=True, default='USD', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('pos_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchant.posterminal')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('destination_bank', models.CharField(choices=[('AFC', 'AFC'), ('AGRIBANK', 'AGRIBANK'), ('BANC ABC', 'BANC ABC'), ('CABS', 'CABS'), ('CBZ', 'CBZ'), ('ECOBANK', 'ECOBANK'), ('FBC', 'FBC'), ('FBC BS', 'FBC BS'), ('FIRST CAPITAL BANK', 'FIRST CAPITAL BANK'), ('GETBUCKS', 'GETBUCKS'), ('NEDBANK', 'NEDBANK'), ('METBANK', 'METBANK'), ('MFS', 'MFS'), ('NBS', 'NBS'), ('NMB', 'NMB'), ('POSB', 'POSB'), ('STANBIC BANK', 'STANBIC BANK'), ('STANDARD CHARTERED', 'STANDARD CHARTERED'), ('STEWARD BANK', 'STEWARD BANK'), ('ONEMONEY', 'ONEMONEY'), ('EMPOWER BANK', 'EMPOWER BANK'), ('ZB BANK', 'ZB BANK')], default='', max_length=100)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchant.merchantprofile')),
            ],
        ),
    ]
