# Generated by Django 3.1.7 on 2021-03-08 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelliPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(default='', max_length=20)),
                ('last_logged_device', models.CharField(max_length=255)),
                ('last_active_time', models.CharField(max_length=255)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='company_type',
            field=models.CharField(choices=[('SOLE TRADER', 'SOLE TRADER'), ('PRIVATE LIMITED COMPANY', 'Private Limited Company'), ('PRIVATE BUSINESS Corporate', 'Private Business Corporate')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='industry',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Airlines / Aviation', 'Airlines / Aviation'), ('Alternative Dispute Resolution', 'Alternative Dispute Resolution'), ('Alternative Medicine', 'Alternative Medicine'), ('Animation', 'Animation'), ('Apparel / Fashion', 'Apparel / Fashion'), ('Architecture / Planning', 'Architecture / Planning'), ('Arts / Crafts', 'Arts / Crafts'), ('Automotive', 'Automotive'), ('Aviation / Aerospace', 'Aviation / Aerospace'), ('Banking / Mortgage', 'Banking / Mortgage'), ('Biotechnology / Greentech', 'Biotechnology / Greentech'), ('Broadcast Media', 'Broadcast Media'), ('Building Materials', 'Building Materials'), ('Business Supplies / Equipment', 'Business Supplies / Equipment'), ('Capital Markets / Hedge Fund / Private Equity', 'Capital Markets / Hedge Fund / Private Equity'), ('Chemicals', 'Chemicals'), ('Civic / Social Organization', 'Civic / Social Organization'), ('Civil Engineering', 'Civil Engineering'), ('Commercial Real Estate', 'Commercial Real Estate'), ('Computer Games', 'Computer Games'), ('Computer Hardware', 'Computer Hardware'), ('Computer Networking', 'Computer Networking'), ('Computer Software / Engineering', 'Computer Software / Engineering'), ('Computer / Network Security', 'Computer / Network Security'), ('Construction', 'Construction'), ('Consumer Electronics', 'Consumer Electronics'), ('Consumer Goods', 'Consumer Goods'), ('Consumer Services', 'Consumer Services'), ('Cosmetics', 'Cosmetics'), ('Dairy', 'Dairy'), ('Defense / Space', 'Defense / Space'), ('Design', 'Design'), ('E - Learning', 'E - Learning'), ('Education Management', 'Education Management'), ('Electrical / Electronic Manufacturing', 'Electrical / Electronic Manufacturing'), ('Entertainment / Movie Production', 'Entertainment / Movie Production'), ('Environmental Services', 'Environmental Services'), ('Events Services', 'Events Services'), ('Executive Office', 'Executive Office'), ('Facilities Services', 'Facilities Services'), ('Farming', 'Farming'), ('Financial Services', 'Financial Services'), ('Fine Art', 'Fine Art'), ('Fishery', 'Fishery'), ('Food Production', 'Food Production'), ('Food / Beverages', 'Food / Beverages'), ('Fundraising', 'Fundraising'), ('Furniture', 'Furniture'), ('Gambling / Casinos', 'Gambling / Casinos'), ('Glass / Ceramics / Concrete', 'Glass / Ceramics / Concrete'), ('Government Administration', 'Government Administration'), ('Government Relations', 'Government Relations'), ('Graphic Design / Web Design', 'Graphic Design / Web Design'), ('Health / Fitness', 'Health / Fitness'), ('Higher Education / Acadamia', 'Higher Education / Acadamia'), ('Hospital / Health Care', 'Hospital / Health Care'), ('Hospitality', 'Hospitality'), ('Human Resources / HR', 'Human Resources / HR'), ('Import / Export', 'Import / Export'), ('Individual / Family Services', 'Individual / Family Services'), ('Industrial Automation', 'Industrial Automation'), ('Information Services', 'Information Services'), ('Information Technology / IT', 'Information Technology / IT'), ('Insurance', 'Insurance'), ('International Affairs', 'International Affairs'), ('International Trade / Development', 'International Trade / Development'), ('Internet', 'Internet'), ('Investment Banking / Venture', 'Investment Banking / Venture'), ('Investment Management / Hedge Fund / Private Equity', 'Investment Management / Hedge Fund / Private Equity'), ('Judiciary', 'Judiciary'), ('Law Enforcement', 'Law Enforcement'), ('Law Practice / Law Firms', 'Law Practice / Law Firms'), ('Legal Services', 'Legal Services'), ('Legislative Office', 'Legislative Office'), ('Leisure / Travel', 'Leisure / Travel'), ('Library', 'Library'), ('Logistics / Procurement', 'Logistics / Procurement'), ('Luxury Goods / Jewelry', 'Luxury Goods / Jewelry'), ('Machinery', 'Machinery'), ('Market Research', 'Market Research'), ('Marketing / Advertising / Sales', 'Marketing / Advertising / Sales'), ('Mechanical or Industrial Engineering', 'Mechanical or Industrial Engineering'), ('Media Production', 'Media Production'), ('Medical ', 'Medical '), ('Military Industry', 'Military Industry'), ('Mining / Metals', 'Mining / Metals'), ('Music', 'Music'), ('Newspapers / Journalism', 'Newspapers / Journalism'), ('Non - Profit / Volunteering', 'Non - Profit / Volunteering'), ('Oil / Energy / Solar / Greentech', 'Oil / Energy / Solar / Greentech'), ('Other Industry', 'Other Industry'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Political Organization', 'Political Organization'), ('Primary / Secondary Education', 'Primary / Secondary Education'), ('Printing', 'Printing'), ('Real Estate / Mortgage', 'Real Estate / Mortgage'), ('Restaurants', 'Restaurants'), ('Retail Industry', 'Retail Industry'), ('Sports', 'Sports'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sender_account', models.CharField(blank=True, default='', max_length=30)),
                ('receiver_account', models.CharField(blank=True, default='', max_length=30)),
                ('destination_bank', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('currency', models.CharField(blank=True, default='USD', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer_merchant', to='merchant.intellipos')),
            ],
        ),
        migrations.AddField(
            model_name='intellipos',
            name='active_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intellipos',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
        ),
    ]
