# Generated by Django 3.1.7 on 2021-03-18 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_hash',
            new_name='password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 11, 15, 53, 97744)),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocks_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 11, 45, 53, 97744)),
        ),
    ]
