# Generated by Django 3.2 on 2022-01-25 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20210412_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTransaction',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('reference', models.CharField(default='', max_length=255, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('selected_card', models.CharField(blank=True, default='', max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_transaction', to='merchant.merchantprofile')),
            ],
        ),
    ]
