# Generated by Django 3.1.7 on 2021-03-18 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20210318_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='pass_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 12, 5, 30, 472956)),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocks_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 12, 35, 30, 472956)),
        ),
    ]
