# Generated by Django 3.1.7 on 2021-03-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20210315_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 16, 16, 38, 362984)),
        ),
    ]
