# Generated by Django 3.1.7 on 2021-03-15 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_user_password_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocked',
            new_name='locked',
        ),
        migrations.AddField(
            model_name='user',
            name='unlocks_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 17, 24, 16, 641844)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 16, 54, 16, 641844)),
        ),
    ]
