# Generated by Django 3.1.7 on 2021-03-17 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20210315_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_change',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 22, 25, 11, 641941)),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocks_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 22, 55, 11, 641941)),
        ),
    ]
