# Generated by Django 3.2 on 2021-05-18 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20210512_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
