# Generated by Django 3.1.7 on 2021-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=255)),
                ('nfc_token', models.CharField(blank=True, default='', max_length=255)),
                ('nfc_pin', models.TextField(blank=True, max_length=255, null=True)),
                ('card_number', models.TextField(blank=True, max_length=20, null=True)),
                ('card_pin', models.TextField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('initial_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
