# Generated by Django 3.2 on 2022-01-27 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0004_auto_20220127_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transctions',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('reference', models.CharField(default='', max_length=255, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('upstream_response', models.TextField()),
                ('extras', models.JSONField(blank=True, null=True)),
                ('pos_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchant.posterminal')),
            ],
        ),
    ]
